bids_dir: '/home/ROBARTS/ataha/graham/scratch/SLAH_BIDS/SLAH_BIDS/bids'
output_dir: '/home/ROBARTS/ataha/graham/scratch/SLAH_BIDS/SLAH_BIDS/derivatives'
template_t1w: 'resources/tpl-MNI152NLin2009cAsym_res-01_T1w.nii.gz'
synthstrip: '/home/ROBARTS/ataha/graham/scratch/afids_auto_preproc/resources/synthstrip.1.3.sif'
            

pybids_inputs:
  t1w:
    filters:
      suffix: T1w
      extension: .nii.gz
      datatype: anat
    wildcards:
    - subject
    - session
    - acquisition
    - task
    
singularity:
  synthstrip: /home/ROBARTS/ataha/graham/scratch/synthstrip.1.3.sif
  
atlas_reg:
    reg_aladin:
        active: True
    greedy:
        active: False
        n_iterations_affine: 100x50x0
        n_iterations_deform: 100x40x20
        grad_sigma: 4.0vox
        warp_sigma: 1.4vox
